[env:teensy41]
platform = teensy@4.18.0
board = teensy41
framework = arduino

board_microros_distro = humble
board_microros_transport = serial

monitor_speed = 115200

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

[env:teensy41-debug]
extends = env:teensy41

build_flags =
    -DTYRANT_ENABLE_DIAGNOSTICS